# Generated by Django 3.2.15 on 2023-11-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('desc', models.TextField()),
            ],
        ),
    ]
